# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: items.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'items.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitems.proto\x12\x05items\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\".\n\x08ItemList\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.items.ItemResponse\"3\n\x0eNewItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x19\n\x0bItemRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xb3\x01\n\x0bItemService\x12\x33\n\x08GetItems\x12\x16.google.protobuf.Empty\x1a\x0f.items.ItemList\x12\x38\n\nCreateItem\x12\x15.items.NewItemRequest\x1a\x13.items.ItemResponse\x12\x35\n\nDeleteItem\x12\x12.items.ItemRequest\x1a\x13.items.ItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'items_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMRESPONSE']._serialized_start=51
  _globals['_ITEMRESPONSE']._serialized_end=112
  _globals['_ITEMLIST']._serialized_start=114
  _globals['_ITEMLIST']._serialized_end=160
  _globals['_NEWITEMREQUEST']._serialized_start=162
  _globals['_NEWITEMREQUEST']._serialized_end=213
  _globals['_ITEMREQUEST']._serialized_start=215
  _globals['_ITEMREQUEST']._serialized_end=240
  _globals['_ITEMSERVICE']._serialized_start=243
  _globals['_ITEMSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
